---
- hosts: webservers
  become: yes
  remote_user: ubuntu
  tasks: 
  - name: Instalando Nginx
    apt:
      name: nginx
      state: present
      update_cache: yes
  - name: Habilitando a inicialização do Ngnix no boot
    service: 
      name: nginx
      enabled: yes
  - name: Iniciando o servico Ngnix
    service:
      name: nginx
      state: started
  - name: Copiando html personalizado
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
    notify: Restartando o Nginx
  handlers:
  - name: Restartando o Nginx
    service:
      name: nginx
      state: restarted
